### ISSUE TITLE
Keep variable after compilation (handlebars) give some errors

### ISSUE THREAD

**Issue by lamualfa** [JPeer264/rcs-webpack-plugin#6]
Other activities run successfully using `rcs-webpack-plugin`. but when I do the following, an error occurs:

My `.hbs` file:

```hbs
<script>
    // See the following issue why I use backslash before helpers:
    // Keep variables for dynamically added in runtime - https://github.com/sagold/handlebars-webpack-plugin/issues/59
    const variable= \{{{addedAtRuntime}}};
</script>

<h1 class="sample">Hello world</h1>
```

**Expected** output (output as `.hbs` file too):

```hbs
<script>
    // Will be rendered dynamically on the server using express-handlebars module
    const variable= {{{addedAtRuntime}}};
</script>

<h1 class="t">Hello world</h1>
```

But the system give error bellow:

```bash
ERROR in   SyntaxError: Unexpected token {
  
  - espree.js:214 Espree.raise
    [rcs-webpack-plugin-examples]/[espree]/lib/espree.js:214:21
  
  - espree.js:259 Espree.unexpected
    [rcs-webpack-plugin-examples]/[espree]/lib/espree.js:259:14
  
  - acorn.js:2776 Espree.pp$3.parseIdent
    [rcs-webpack-plugin-examples]/[acorn]/dist/acorn.js:2776:12
  
  - acorn.js:2582 Espree.pp$3.parsePropertyName
    [rcs-webpack-plugin-examples]/[acorn]/dist/acorn.js:2582:107

  ... and more
```

Can you add a `ignore rule` like `eslint` ignore or is there a better solution?

<br/>
<br/>

Related:

- https://github.com/sagold/handlebars-webpack-plugin/issues/59

**Comment by JPeer264** [comment]
This is because espree cannot handle handlebars variables. I will check how I can solve this problem.

**Comment by JPeer264** [comment]
I didn't come up for a more elegant solution than the way I did now. It should work now if you set the option `experimentalHandlebarsVariables` to `true` in v`1.4.0`. Hopefully, all your issues are resolved now :)

**Comment by JPeer264** [comment]
Also, feel free to reopen if you think this issue is not yet resolved.
