### ISSUE TITLE
Add support for html-webpack-plugin 4.0.0-beta.11

### ISSUE THREAD

**Issue by lamualfa** [JPeer264/rcs-webpack-plugin#7]
`rcs-webpack-plugin` not working with `html-webpack-plugin` version `4.0.0-beta.11`. `rcs-webpack-plugin` only change selector in `css` and `js` file, not working in `hbs` file.

**Comment by JPeer264** [comment]
Alright, I take a look into the beta.

**Comment by JPeer264** [comment]
`html-webpack-plugin` had some changes in their hooks api. It should work now with v`1.3.0`

**Comment by lamualfa** [comment]
> `html-webpack-plugin` had some changes in their hooks api. It should work now with v`1.3.0`

Does `rcs-webpack-plugin` version `1.3.0` still support `html-webpack-plugin` in previous version?

**Comment by JPeer264** [comment]
Sure, it also supports v3 of `html-webpack-plugin`
