### ISSUE TITLE
How do I ignore certain selectors so they don't replace them?

### ISSUE THREAD

**Issue by lamualfa** [JPeer264/rcs-webpack-plugin#8]
Examples:
```html
<styles>
#txt {
 color: blue;
}
</styles>

<span id="txt">Hello</span>
```
Prevent the `txt` id from being renamed. I don't see any suitable options that can be passed to the main library [node-rcs-core](https://github.com/JPeer264/node-rcs-core/). The `fillLibrariesOptions.ignoreCssVariables` property seems to be ignoring the entire selector instead

**Comment by JPeer264** [comment]
This is not possible with the options. For that you have to import `rcs-core` and exclude the selectors:

```js
const rcs = require('rcs-core');

// string
rcs.selectorLibrary.setExclude('txt');

// string[]
rcs.selectorLibrary.setExclude(['txt', 'another-txt']);

// RegExp
rcs.selectorLibrary.setExclude(/^txt$/);
```

You have much more options for the selectorLibrary in the [docs](https://github.com/JPeer264/node-rcs-core/blob/7e3ebb872964f49bf82c84f6920005610a3d252a/docs/api/selectorlibrary.md#setexclude).

There are also more functions for keyframes or attributes: [here](https://github.com/JPeer264/node-rcs-core/tree/7e3ebb872964f49bf82c84f6920005610a3d252a/docs/api)

I will add this into the readme too.

**Comment by JPeer264** [comment]
Also make sure you met the [peerDependency requirements](https://github.com/JPeer264/rcs-webpack-plugin/blob/master/package.json#L30)
